name: zudellio
static_sites:
  - name: interface
    source_dir: interface
    github:
      repo: JonZudell/zudellio
      branch: main
    build_command: npm run build
    output_dir: dist
    index_document: index.html
    catchall_document: index.html
    routes:
      - path: /
